

GET http://localhost:3051/films/allseries HTTP/1.1

###

GET http://localhost:3051/films/allmovies HTTP/1.1

###

POST http://localhost:3051/films/newmovie HTTP/1.1
content-type: application/json

{
    "title_movie": "Scooby-Doo",
    "description_movie": "Deux ans après s'être résolus à fermer la Mystère & Cie, le super-chien Scooby-Doo et ses amis Fred, Daphné, Sammy et Véra se retrouvent sur Spooky Island. Les 5 limiers au flair inimitable ont été...",
    "url_image_movie": "https://image.tmdb.org/t/p/w600_and_h900_bestv2/hNER9ZurlRPmcM2uqkLNXXgJzFk.jpg",
    "release_year": "2002-01-01",
    "id_category": 2
}